## Imports

In [1]:
import numpy as np
import pandas as pd
import optuna
import matplotlib.pyplot as plt
import seaborn as sns
import mlflow
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.metrics import root_mean_squared_error

/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_parquet("../data/green_tripdata_2026-01.parquet")

## Global Variables

In [3]:
TRACKING_URI = "http://127.0.0.1:5000"

## Exploring the Data

In [4]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,1,2026-01-01 00:27:58,2026-01-01 00:55:16,N,1.0,65,233,2.0,6.20,31.7,...,1.5,7.5,0.0,NaN,1.0,45.20,1.0,1.0,2.75,0.75
1,2,2026-01-01 00:44:33,2026-01-01 01:32:56,N,5.0,66,188,5.0,5.36,50.0,...,0.0,10.2,0.0,NaN,1.0,61.20,1.0,2.0,0.00,0.00
2,1,2026-01-01 00:23:45,2026-01-01 00:45:03,N,1.0,65,179,4.0,10.60,41.5,...,1.5,2.0,0.0,NaN,1.0,46.00,1.0,1.0,0.00,0.00
3,1,2026-01-01 00:44:33,2026-01-01 01:00:45,N,1.0,42,141,1.0,4.20,19.8,...,1.5,0.0,0.0,NaN,1.0,25.05,2.0,1.0,2.75,0.00
4,2,2026-01-01 00:46:04,2026-01-01 01:04:40,N,1.0,95,82,1.0,2.76,19.1,...,0.5,0.0,0.0,NaN,1.0,21.60,2.0,1.0,0.00,0.00

In [5]:
df.shape

(40272, 21)

In [6]:
df.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='object')

In [7]:
df.isnull().sum()

VendorID                     0
lpep_pickup_datetime         0
lpep_dropoff_datetime        0
store_and_fwd_flag        5414
RatecodeID                5414
PULocationID                 0
DOLocationID                 0
passenger_count           5414
trip_distance                0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
ehail_fee                40272
improvement_surcharge        0
total_amount                 0
payment_type              5414
trip_type                 5415
congestion_surcharge      5414
cbd_congestion_fee           0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40272 entries, 0 to 40271
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               40272 non-null  int32
 1   lpep_pickup_datetime   40272 non-null  datetime64[us]
 2   lpep_dropoff_datetime  40272 non-null  datetime64[us]
 3   store_and_fwd_flag     34858 non-null  object
 4   RatecodeID             34858 non-null  float64
 5   PULocationID           40272 non-null  int32
 6   DOLocationID           40272 non-null  int32
 7   passenger_count        34858 non-null  float64
 8   trip_distance          40272 non-null  float64
 9   fare_amount            40272 non-null  float64
 10  extra                  40272 non-null  float64
 11  mta_tax                40272 non-null  float64
 12  tip_amount             40272 non-null  float64
 13  tolls_amount           40272 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  40272 non-null  float64
 16  total_amount           40272 non-null  float64
 17  payment_type           34858 non-null  float64
 18  trip_type              34857 non-null  float64
 19  congestion_surcharge   34858 non-null  float64
 20  cbd_congestion_fee     40272 non-null  float64
dtypes: datetime64[us](2), float64(15), int32(3), object(1)
memory usage: 6.0+ MB

In [9]:
df.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,40272.000000,40272,40272,34858.000000,40272.000000,40272.000000,34858.000000,40272.000000,40272.000000,40272.000000,40272.000000,40272.000000,40272.000000,0.0,40272.000000,40272.000000,34858.000000,34857.000000,34858.000000,40272.000000
mean,2.279897,2026-01-16 22:38:57.806366,2026-01-16 22:59:02.332389,1.207212,96.190480,141.878352,1.298382,12.551243,16.006925,0.823550,0.561687,2.476605,0.260190,NaN,0.922189,24.195461,1.259711,1.046562,0.851383,0.058179
min,1.000000,2025-12-27 16:49:41,2025-12-27 17:02:11,1.000000,1.000000,1.000000,0.000000,0.000000,-70.000000,-7.500000,-0.500000,-2.520000,0.000000,NaN,-1.000000,-76.500000,1.000000,1.000000,0.000000,0.000000
25%,2.000000,2026-01-09 11:18:24,2026-01-09 11:37:25.250000,1.000000,74.000000,74.000000,1.000000,1.200000,8.600000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,14.600000,1.000000,1.000000,0.000000,0.000000
50%,2.000000,2026-01-16 14:27:16.500000,2026-01-16 14:47:26.500000,1.000000,75.000000,140.000000,1.000000,1.960000,12.800000,0.000000,0.500000,2.000000,0.000000,NaN,1.000000,20.000000,1.000000,1.000000,0.000000,0.000000
75%,2.000000,2026-01-23 19:37:11.500000,2026-01-23 19:55:24.250000,1.000000,97.000000,229.000000,1.000000,3.470000,19.100000,1.000000,0.500000,3.770000,0.000000,NaN,1.000000,28.860000,1.000000,1.000000,2.750000,0.000000
max,6.000000,2026-02-01 21:08:36,2026-02-01 21:15:02,99.000000,265.000000,265.000000,9.000000,179830.920000,960.000000,7.500000,4.250000,300.000000,85.000000,NaN,1.000000,961.000000,4.000000,2.000000,2.750000,0.750000
std,1.233095,NaN,NaN,1.018101,55.683047,77.583150,0.950439,1033.875580,14.951959,1.332193,0.321908,3.564317,1.583427,NaN,0.245158,17.177547,0.471217,0.210701,1.271401,0.200626

In [10]:
df.drop('ehail_fee',axis=1,inplace=True)

## Creating the target variable

In [11]:
df = df.dropna()

In [12]:
df.shape

(34857, 20)

In [13]:
df['duration'] = ((df['lpep_dropoff_datetime']-df['lpep_pickup_datetime']).dt.total_seconds())/60

In [14]:
df['duration']# This is the duration in minutes.

0        27.300000
1        48.383333
2        21.300000
3        16.200000
4        18.600000
           ...
34853     5.883333
34854     8.733333
34855     4.633333
34856     8.833333
34857    10.483333
Name: duration, Length: 34857, dtype: float64

In [15]:
#Since most of thr duration is below 60 minutes , hence keep it below 60 minutes
df = df[(df['duration']>=0) & (df['duration']<=60)]

In [16]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,duration
0,1,2026-01-01 00:27:58,2026-01-01 00:55:16,N,1.0,65,233,2.0,6.20,31.7,...,1.5,7.5,0.0,1.0,45.20,1.0,1.0,2.75,0.75,27.300000
1,2,2026-01-01 00:44:33,2026-01-01 01:32:56,N,5.0,66,188,5.0,5.36,50.0,...,0.0,10.2,0.0,1.0,61.20,1.0,2.0,0.00,0.00,48.383333
2,1,2026-01-01 00:23:45,2026-01-01 00:45:03,N,1.0,65,179,4.0,10.60,41.5,...,1.5,2.0,0.0,1.0,46.00,1.0,1.0,0.00,0.00,21.300000
3,1,2026-01-01 00:44:33,2026-01-01 01:00:45,N,1.0,42,141,1.0,4.20,19.8,...,1.5,0.0,0.0,1.0,25.05,2.0,1.0,2.75,0.00,16.200000
4,2,2026-01-01 00:46:04,2026-01-01 01:04:40,N,1.0,95,82,1.0,2.76,19.1,...,0.5,0.0,0.0,1.0,21.60,2.0,1.0,0.00,0.00,18.600000

In [17]:
df.shape

(34572, 21)

In [18]:
df = df[df['passenger_count']>0]

In [19]:
df.shape

(34014, 21)

## Feature Engineering

In [20]:
df.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount',
       'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee', 'duration'],
      dtype='object')

In [21]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,duration
0,1,2026-01-01 00:27:58,2026-01-01 00:55:16,N,1.0,65,233,2.0,6.20,31.7,...,1.5,7.5,0.0,1.0,45.20,1.0,1.0,2.75,0.75,27.300000
1,2,2026-01-01 00:44:33,2026-01-01 01:32:56,N,5.0,66,188,5.0,5.36,50.0,...,0.0,10.2,0.0,1.0,61.20,1.0,2.0,0.00,0.00,48.383333
2,1,2026-01-01 00:23:45,2026-01-01 00:45:03,N,1.0,65,179,4.0,10.60,41.5,...,1.5,2.0,0.0,1.0,46.00,1.0,1.0,0.00,0.00,21.300000
3,1,2026-01-01 00:44:33,2026-01-01 01:00:45,N,1.0,42,141,1.0,4.20,19.8,...,1.5,0.0,0.0,1.0,25.05,2.0,1.0,2.75,0.00,16.200000
4,2,2026-01-01 00:46:04,2026-01-01 01:04:40,N,1.0,95,82,1.0,2.76,19.1,...,0.5,0.0,0.0,1.0,21.60,2.0,1.0,0.00,0.00,18.600000

In [22]:
df['pickup_hour'] = df['lpep_pickup_datetime'].dt.hour

In [23]:
df['pickup_day'] = df['lpep_pickup_datetime'].dt.day

In [24]:
df['pickup_month'] = df['lpep_pickup_datetime'].dt.month

In [25]:
df['pickup_weekday'] = df['lpep_pickup_datetime'].dt.weekday

In [26]:
df['PU_DO'] = ((df['PULocationID'].astype(str))+"_"+ (df['DOLocationID'].astype(str)))

In [27]:
df.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount',
       'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee', 'duration', 'pickup_hour', 'pickup_day',
       'pickup_month', 'pickup_weekday', 'PU_DO'],
      dtype='object')

In [28]:
numerical_features = [

        # time features
        "pickup_hour",
        "pickup_day",
        "pickup_month",
        "pickup_weekday",
        "passenger_count",
        "trip_distance",
    ]

categorical_features = [
    "PULocationID",
    "DOLocationID",
    "PU_DO"
]

In [29]:
X = df[numerical_features+categorical_features]
y = df['duration']

In [30]:
X.head()

,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO
0,0,1,1,3,2.0,6.20,65,233,65_233
1,0,1,1,3,5.0,5.36,66,188,66_188
2,0,1,1,3,4.0,10.60,65,179,65_179
3,0,1,1,3,1.0,4.20,42,141,42_141
4,0,1,1,3,1.0,2.76,95,82,95_82

## Splitting the Data and doing Scaling

In [31]:
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.3,random_state=42)
X_test,X_val,y_test,y_val = train_test_split(X_val,y_val,test_size=0.5,random_state=42)

In [32]:
X_train.head()

,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO
11202,15,11,1,6,1.0,2.87,74,239,74_239
15934,13,15,1,3,1.0,0.96,166,152,166_152
26636,10,24,1,5,1.0,1.72,74,75,74_75
31073,2,29,1,3,1.0,1.21,129,226,129_226
24904,22,22,1,3,1.0,8.17,95,16,95_16

In [35]:
check = X_train.iloc[0].to_dict()

In [37]:
check.keys()

dict_keys(['pickup_hour', 'pickup_day', 'pickup_month', 'pickup_weekday', 'passenger_count', 'trip_distance', 'PULocationID', 'DOLocationID', 'PU_DO'])

In [38]:
u = pd.DataFrame([{'pickup_hour': 15,
'pickup_day': 11,
'pickup_month': 1,
'pickup_weekday': 6,
'passenger_count': 1.0,
'trip_distance': 2.87,
'PULocationID': 74,
'DOLocationID': 239,
'PU_DO': '74_239'}])

In [39]:
u

,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO
0,15,11,1,6,1.0,2.87,74,239,74_239

In [42]:
list(u.keys())

['pickup_hour',
 'pickup_day',
 'pickup_month',
 'pickup_weekday',
 'passenger_count',
 'trip_distance',
 'PULocationID',
 'DOLocationID',
 'PU_DO']

In [35]:
y_train.head()

11202    19.566667
15934     7.866667
26636     9.816667
31073     6.383333
24904    15.933333
Name: duration, dtype: float64

In [37]:
reference_data = pd.concat([X_train,y_train],axis=1)

In [39]:
reference_data.to_csv("../monitoring/data/reference_data.csv")

In [33]:
y_train.head()

11202    19.566667
15934     7.866667
26636     9.816667
31073     6.383333
24904    15.933333
Name: duration, dtype: float64

In [33]:
# import numpy as np

# print("Positive infinity:", np.isposinf(X_train).sum().sum())
# print("Negative infinity:", np.isneginf(X_train).sum().sum())

In [34]:
# inf_columns = X_train.columns[
#     np.isinf(X_train.select_dtypes(include=np.number)).any()
# ]

# print(inf_columns)

In [35]:
column_transformer = ColumnTransformer([
    ("num", StandardScaler(), numerical_features),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
])

## Model building and Experiment tracking

In [36]:
mlflow.set_tracking_uri(TRACKING_URI)
mlflow.set_experiment("trip-duration-prediction")

<Experiment: artifact_location='/Users/akhilendra.singh/Documents/Trip-Duration-Prediction/model-building/artifacts/1', creation_time=1789375472721, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1789375472721, lifecycle_stage='active', name='trip-duration-prediction', tags={}, trace_location=None, workspace='default'>

In [37]:
def get_params(model_name, trial):
    if model_name == 'Linear Regression':
        return {}
        
    elif model_name == 'SVR':  
        return {
            'C': trial.suggest_float('C', 1e-3, 1e2, log=True),
            'epsilon': trial.suggest_float('epsilon', 1e-4, 1.0, log=True),
            'kernel': trial.suggest_categorical('kernel', ['rbf', 'linear', 'poly']),
        }
        
    elif model_name == 'Decision Tree':
        return {
            'max_depth': trial.suggest_int('max_depth', 3, 20),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 20),
        }
        
    elif model_name == 'Random Forest':
        return {
            'n_estimators': trial.suggest_int('n_estimators', 100, 400, step=50),
            'max_depth': trial.suggest_int('max_depth', 3, 20),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 20),
        }
        
    elif model_name == 'Gradient Boost':
        return {
            'n_estimators': trial.suggest_int('n_estimators', 50, 300, step=50),
            'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
            'max_depth': trial.suggest_int('max_depth', 3, 10),
        }
        
    else:
        raise ValueError(f"Unknown model name: {model_name}")

In [38]:
y_val.head()

9003      9.350000
25646    30.516667
1487     14.100000
7405     29.400000
19968    40.350000
Name: duration, dtype: float64

In [39]:
def get_model(model_name,params):
    if model_name == 'Linear Regression':
        model = LinearRegression(**params)
            
    elif model_name == 'SVR':  
        model = SVR(**params)
     
    elif model_name == 'Decision Tree':  
        model = DecisionTreeRegressor(**params)

    elif model_name == 'Random Forest':  
        model = RandomForestRegressor(**params)

    elif model_name == 'Gradient Boost':  
        model = GradientBoostingRegressor(**params)
    else:
        raise ValueError(f"Unknown model name: {model_name}")

    return model

In [40]:
def train_model(model,n_trials):

    def objective(trial):
        params = get_params(model,trial)
        classifier = get_model(model,params)
        pipeline = Pipeline([
        ('preprocessor',column_transformer),
        ('model',classifier)
        ])
        with mlflow.start_run(nested=True):
            mlflow.log_params(params)
            pipeline.fit(X_train,y_train)
            y_pred = pipeline.predict(X_val)
            rmse = root_mean_squared_error(y_val,y_pred)
            mlflow.log_metric("rmse",rmse)

        return rmse
    
    with mlflow.start_run(run_name=f"{model}"):
        mlflow.log_param('model',model)
        study = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
        study.optimize(objective, n_trials)

        mlflow.log_params({f"best_{k}": v for k, v in study.best_params.items()})
        mlflow.log_metric("best-rmse",study.best_value)

In [41]:
models = ['Linear Regression','SVR','Decision Tree','Random Forest','Gradient Boost']

for model in models:
    n_trials = 10 if model in ['Random Forest','Gradient Boost','SVR'] else 20
    train_model(model,n_trials)

[I 2026-09-15 11:04:12,030] A new study created in memory with name: no-name-5db44d2a-ef83-42b1-b5af-7a010c13d101
[I 2026-09-15 11:04:12,186] Trial 0 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:12,319] Trial 1 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run able-mink-607 at: http://127.0.0.1:5000/#/experiments/1/runs/86265345d8e044d787269df93bda9385
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run trusting-bear-693 at: http://127.0.0.1:5000/#/experiments/1/runs/c58292c1941c458b89952a9ed832f290
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:12,450] Trial 2 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:12,579] Trial 3 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run blushing-grouse-115 at: http://127.0.0.1:5000/#/experiments/1/runs/3ce593b9f1074b5e9045605a121f30c9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run marvelous-wren-490 at: http://127.0.0.1:5000/#/experiments/1/runs/79a8210e44cc414d9abfac0936b9c7e7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:12,711] Trial 4 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:12,842] Trial 5 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run blushing-gnat-295 at: http://127.0.0.1:5000/#/experiments/1/runs/315c7526c208408db5f065f745724da0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run salty-mule-205 at: http://127.0.0.1:5000/#/experiments/1/runs/ef794fb02ea343759801caefe8200bed
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:12,974] Trial 6 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:13,106] Trial 7 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run stylish-dolphin-78 at: http://127.0.0.1:5000/#/experiments/1/runs/ea568684d2534b059efd770e69b1f264
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run whimsical-fawn-939 at: http://127.0.0.1:5000/#/experiments/1/runs/50b5347af09542e89d0be4958a01a060
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:13,241] Trial 8 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:13,372] Trial 9 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run big-donkey-727 at: http://127.0.0.1:5000/#/experiments/1/runs/d8e02eb2a56f42d097dd721977d9fada
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run righteous-quail-25 at: http://127.0.0.1:5000/#/experiments/1/runs/4c6a6389a86346c3a723ac996ade6308
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:13,502] Trial 10 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:13,631] Trial 11 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run stylish-gull-438 at: http://127.0.0.1:5000/#/experiments/1/runs/fa253ffc9dce409b92aa937e35fb5f75
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run chill-grouse-534 at: http://127.0.0.1:5000/#/experiments/1/runs/f9a956d5301d4c589f54cb5d53006d89
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:13,766] Trial 12 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:13,903] Trial 13 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run powerful-dolphin-45 at: http://127.0.0.1:5000/#/experiments/1/runs/2a38fc1b92de4c54bf4ed6cf048fd687
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run judicious-bee-429 at: http://127.0.0.1:5000/#/experiments/1/runs/5de10efdab884a20b5869cd27ffc66ce
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:14,071] Trial 14 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:14,203] Trial 15 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run awesome-koi-90 at: http://127.0.0.1:5000/#/experiments/1/runs/06b0656b2b914f10a567d9bb9f6266e6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run upset-moth-324 at: http://127.0.0.1:5000/#/experiments/1/runs/a5baab01045d4cf88f6b46461fdfa2d7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:14,340] Trial 16 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:14,469] Trial 17 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.

🏃 View run enchanting-rat-589 at: http://127.0.0.1:5000/#/experiments/1/runs/c7787300ef2349ee95d746a0ac468bca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run worried-tern-825 at: http://127.0.0.1:5000/#/experiments/1/runs/814c62748bed49bf959cf2cf5050ecbb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:14,601] Trial 18 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:14,732] Trial 19 finished with value: 5.297774718297283 and parameters: {}. Best is trial 0 with value: 5.297774718297283.
[I 2026-09-15 11:04:14,762] A new study created in memory with name: no-name-d96d90a3-d2d6-4a64-8369-e50511dc0d9d

🏃 View run beautiful-grouse-212 at: http://127.0.0.1:5000/#/experiments/1/runs/ab275d8a27cc4392a6baefe088e62bda
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run nimble-lark-1 at: http://127.0.0.1:5000/#/experiments/1/runs/cb66bef5f3e44cc5a92eb4b8b99d54f5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run Linear Regression at: http://127.0.0.1:5000/#/experiments/1/runs/6c1a92569ff349a3962a51cbf10a811f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:04:27,678] Trial 0 finished with value: 5.562499761835467 and parameters: {'C': 0.0828223326431111, 'epsilon': 0.020720182542497644, 'kernel': 'linear'}. Best is trial 0 with value: 5.562499761835467.

🏃 View run spiffy-skink-836 at: http://127.0.0.1:5000/#/experiments/1/runs/8bf95e5e920b4a90bd10655b9e3eb57a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:05:33,816] Trial 1 finished with value: 5.358829887040908 and parameters: {'C': 8.939751714668523, 'epsilon': 0.1459180993215083, 'kernel': 'linear'}. Best is trial 1 with value: 5.358829887040908.

🏃 View run caring-dog-900 at: http://127.0.0.1:5000/#/experiments/1/runs/56991c3954e34cfeac4e49ea96bd8aca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:05:45,562] Trial 2 finished with value: 5.965902228341334 and parameters: {'C': 0.0029849153596051103, 'epsilon': 0.4612590727163809, 'kernel': 'linear'}. Best is trial 1 with value: 5.358829887040908.

🏃 View run unruly-dog-971 at: http://127.0.0.1:5000/#/experiments/1/runs/c41f310bf32541de945c367f1d673125
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:05:59,778] Trial 3 finished with value: 5.159174584574264 and parameters: {'C': 0.3098577749462275, 'epsilon': 0.0002567508510697899, 'kernel': 'rbf'}. Best is trial 3 with value: 5.159174584574264.

🏃 View run puzzled-mink-440 at: http://127.0.0.1:5000/#/experiments/1/runs/da119c34727f4fa3829e01542cc6fb49
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:06:12,395] Trial 4 finished with value: 6.063654118523336 and parameters: {'C': 0.0017901189910099254, 'epsilon': 0.022001663085923766, 'kernel': 'linear'}. Best is trial 3 with value: 5.159174584574264.

🏃 View run illustrious-hen-862 at: http://127.0.0.1:5000/#/experiments/1/runs/17ade5a0ed02439483d82abbcd0c9f52
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:07:56,485] Trial 5 finished with value: 4.548722488367539 and parameters: {'C': 37.22622766508552, 'epsilon': 0.0035413396633088286, 'kernel': 'rbf'}. Best is trial 5 with value: 4.548722488367539.

🏃 View run smiling-snail-769 at: http://127.0.0.1:5000/#/experiments/1/runs/aa83b07e97e742e1a80b0eaab3bca607
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:10,595] Trial 6 finished with value: 7.866417832285388 and parameters: {'C': 0.006266657481282181, 'epsilon': 0.11861761184356807, 'kernel': 'rbf'}. Best is trial 5 with value: 4.548722488367539.

🏃 View run tasteful-hog-218 at: http://127.0.0.1:5000/#/experiments/1/runs/3eacd272700e4985964ec65a4ae07faf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:26,198] Trial 7 finished with value: 5.346423704513113 and parameters: {'C': 0.5355952673370781, 'epsilon': 0.0007370546935623639, 'kernel': 'linear'}. Best is trial 5 with value: 4.548722488367539.

🏃 View run classy-shark-444 at: http://127.0.0.1:5000/#/experiments/1/runs/c1aa9bfb09d147a0a0cc7ca17b331032
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:44,238] Trial 8 finished with value: 4.6014897204896625 and parameters: {'C': 3.382320227242093, 'epsilon': 0.09249385578784791, 'kernel': 'rbf'}. Best is trial 5 with value: 4.548722488367539.

🏃 View run selective-toad-942 at: http://127.0.0.1:5000/#/experiments/1/runs/ec6e2888b30649248503a74be3d3a5e2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:58,455] Trial 9 finished with value: 8.151109936319932 and parameters: {'C': 0.004357121052299903, 'epsilon': 0.003376925577920022, 'kernel': 'rbf'}. Best is trial 5 with value: 4.548722488367539.
[I 2026-09-15 11:08:58,488] A new study created in memory with name: no-name-6edef80d-8a58-423f-b645-fafc3802aadf

🏃 View run inquisitive-duck-558 at: http://127.0.0.1:5000/#/experiments/1/runs/f87dd5169c414c3e9599e273706606fa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run SVR at: http://127.0.0.1:5000/#/experiments/1/runs/d89c4805aace477d99fd9e446e148ce3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:58,689] Trial 0 finished with value: 4.851186224314046 and parameters: {'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 15}. Best is trial 0 with value: 4.851186224314046.
[I 2026-09-15 11:08:58,865] Trial 1 finished with value: 4.812469118074464 and parameters: {'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 18}. Best is trial 1 with value: 4.812469118074464.

🏃 View run delicate-rook-538 at: http://127.0.0.1:5000/#/experiments/1/runs/195ffada2b0641228b1fae71698ddeb6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run sneaky-robin-831 at: http://127.0.0.1:5000/#/experiments/1/runs/01188d32e523440a8e94976758a1e90d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:59,103] Trial 2 finished with value: 5.008541766656706 and parameters: {'max_depth': 17, 'min_samples_split': 16, 'min_samples_leaf': 3}. Best is trial 1 with value: 4.812469118074464.
[I 2026-09-15 11:08:59,231] Trial 3 finished with value: 4.9191023820361455 and parameters: {'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 1 with value: 4.812469118074464.

🏃 View run languid-ray-418 at: http://127.0.0.1:5000/#/experiments/1/runs/5922194ff4bb452ab58d89f74bc61341
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run sedate-calf-573 at: http://127.0.0.1:5000/#/experiments/1/runs/dfb3738d087b430184377c52f75fa1e4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:59,313] Trial 4 finished with value: 5.233339125574331 and parameters: {'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 9}. Best is trial 1 with value: 4.812469118074464.

🏃 View run upset-sheep-412 at: http://127.0.0.1:5000/#/experiments/1/runs/637e9a1a8fe246a193cf6baf2b59c302
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:59,516] Trial 5 finished with value: 4.866186105209223 and parameters: {'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 13}. Best is trial 1 with value: 4.812469118074464.
[I 2026-09-15 11:08:59,643] Trial 6 finished with value: 4.857898134809832 and parameters: {'max_depth': 9, 'min_samples_split': 18, 'min_samples_leaf': 12}. Best is trial 1 with value: 4.812469118074464.

🏃 View run efficient-doe-450 at: http://127.0.0.1:5000/#/experiments/1/runs/ccec08c2f54c4b7b9825d45beaddef4e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run lyrical-snail-517 at: http://127.0.0.1:5000/#/experiments/1/runs/a2c3b30b97bb4021b8f0d03fd665b7c9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:08:59,755] Trial 7 finished with value: 4.940200770881441 and parameters: {'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 11}. Best is trial 1 with value: 4.812469118074464.
[I 2026-09-15 11:08:59,866] Trial 8 finished with value: 4.947751669366529 and parameters: {'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 1 with value: 4.812469118074464.

🏃 View run magnificent-deer-669 at: http://127.0.0.1:5000/#/experiments/1/runs/021dc4afcd334415b6e7c3c39615be82
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run funny-shrew-743 at: http://127.0.0.1:5000/#/experiments/1/runs/fbb5ee4f54cd4c30a09c6935dad8eda2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:00,065] Trial 9 finished with value: 4.820455216175297 and parameters: {'max_depth': 19, 'min_samples_split': 15, 'min_samples_leaf': 19}. Best is trial 1 with value: 4.812469118074464.

🏃 View run capricious-crow-348 at: http://127.0.0.1:5000/#/experiments/1/runs/29a037c2db0148ab884564d77a50dbae
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:00,305] Trial 10 finished with value: 5.16193849483186 and parameters: {'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 1 with value: 4.812469118074464.

🏃 View run nosy-finch-735 at: http://127.0.0.1:5000/#/experiments/1/runs/c7b15bc7ae8d4c2c92d9ee1d3866c556
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run thoughtful-koi-404 at: http://127.0.0.1:5000/#/experiments/1/runs/e55e2e2ea5d84ea9841018c7ced3862b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:00,503] Trial 11 finished with value: 4.8232891652130965 and parameters: {'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 19}. Best is trial 1 with value: 4.812469118074464.
[I 2026-09-15 11:09:00,638] Trial 12 finished with value: 4.816707643067754 and parameters: {'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 20}. Best is trial 1 with value: 4.812469118074464.
[I 2026-09-15 11:09:00,788] Trial 13 finished with value: 4.807008988158594 and parameters: {'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 18}. Best is trial 13 with value: 4.807008988158594.

🏃 View run efficient-stag-828 at: http://127.0.0.1:5000/#/experiments/1/runs/ad604883cd7c44e58225b2bd69a4babd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run indecisive-chimp-830 at: http://127.0.0.1:5000/#/experiments/1/runs/66a7fe50a59a435c8716e368688d2292
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:00,914] Trial 14 finished with value: 4.822771443233402 and parameters: {'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 17}. Best is trial 13 with value: 4.807008988158594.
[I 2026-09-15 11:09:01,015] Trial 15 finished with value: 5.020085886063581 and parameters: {'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 18}. Best is trial 13 with value: 4.807008988158594.

🏃 View run invincible-wren-376 at: http://127.0.0.1:5000/#/experiments/1/runs/e235ba891b8c4f13a62657eb5303633d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run sneaky-newt-287 at: http://127.0.0.1:5000/#/experiments/1/runs/f7d2b144118840719a3d91986b05bb74
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:01,118] Trial 16 finished with value: 5.030728770965474 and parameters: {'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 12}. Best is trial 13 with value: 4.807008988158594.
[I 2026-09-15 11:09:01,289] Trial 17 finished with value: 4.815529840270092 and parameters: {'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 16}. Best is trial 13 with value: 4.807008988158594.

🏃 View run redolent-robin-883 at: http://127.0.0.1:5000/#/experiments/1/runs/c499c48429dc48fe86621003fb0118ce
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run gifted-shoat-196 at: http://127.0.0.1:5000/#/experiments/1/runs/84788a6f86394268a2eb35c767d62925
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:01,462] Trial 18 finished with value: 4.806084470053386 and parameters: {'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 20}. Best is trial 18 with value: 4.806084470053386.
[I 2026-09-15 11:09:01,647] Trial 19 finished with value: 4.859011220983752 and parameters: {'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 13}. Best is trial 18 with value: 4.806084470053386.

🏃 View run smiling-frog-349 at: http://127.0.0.1:5000/#/experiments/1/runs/288e2953d9ed431187eb625038cb62b5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run skittish-duck-784 at: http://127.0.0.1:5000/#/experiments/1/runs/2abc162f8b9c40279bc95834ee24bc94
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:01,679] A new study created in memory with name: no-name-16d88a55-6ea3-4263-9842-f3e006346b72

🏃 View run Decision Tree at: http://127.0.0.1:5000/#/experiments/1/runs/015bdfa70d994b30b6928be705bf4ad4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:14,052] Trial 0 finished with value: 4.610529790127526 and parameters: {'n_estimators': 150, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 10}. Best is trial 0 with value: 4.610529790127526.

🏃 View run delicate-penguin-846 at: http://127.0.0.1:5000/#/experiments/1/runs/c287090847414e00a9604ed329a902e1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:29,426] Trial 1 finished with value: 4.771096489985258 and parameters: {'n_estimators': 350, 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 11}. Best is trial 0 with value: 4.610529790127526.

🏃 View run unruly-swan-44 at: http://127.0.0.1:5000/#/experiments/1/runs/71d9be9064484426b015a1ff9ce10c49
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:35,754] Trial 2 finished with value: 4.826692338321679 and parameters: {'n_estimators': 150, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 1}. Best is trial 0 with value: 4.610529790127526.

🏃 View run placid-snake-619 at: http://127.0.0.1:5000/#/experiments/1/runs/29746010788c4ed289faddd48a880702
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:50,358] Trial 3 finished with value: 4.632589808594164 and parameters: {'n_estimators': 150, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 17}. Best is trial 0 with value: 4.610529790127526.

🏃 View run chill-perch-739 at: http://127.0.0.1:5000/#/experiments/1/runs/047af220932e4884a9efe645d0139800
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:09:52,722] Trial 4 finished with value: 5.463117575579091 and parameters: {'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 15, 'min_samples_leaf': 16}. Best is trial 0 with value: 4.610529790127526.

🏃 View run gentle-ape-628 at: http://127.0.0.1:5000/#/experiments/1/runs/cf889282309940bdae82c0443d4e1b10
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:10:10,954] Trial 5 finished with value: 4.603293986293203 and parameters: {'n_estimators': 250, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 6}. Best is trial 5 with value: 4.603293986293203.

🏃 View run youthful-gnat-128 at: http://127.0.0.1:5000/#/experiments/1/runs/bbe69e4ed8044fee8bac0ea27d87bbf2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:10:23,163] Trial 6 finished with value: 4.8743292340615145 and parameters: {'n_estimators': 350, 'max_depth': 7, 'min_samples_split': 13, 'min_samples_leaf': 19}. Best is trial 5 with value: 4.603293986293203.

🏃 View run silent-gull-872 at: http://127.0.0.1:5000/#/experiments/1/runs/bb520a153cb548ed8fc437dda7a63874
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:10:39,698] Trial 7 finished with value: 4.640472601352096 and parameters: {'n_estimators': 250, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 5 with value: 4.603293986293203.

🏃 View run painted-snipe-851 at: http://127.0.0.1:5000/#/experiments/1/runs/0c2a24d4cee543b98bc112dee14cde81
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:11:21,489] Trial 8 finished with value: 4.546268886233306 and parameters: {'n_estimators': 350, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 8 with value: 4.546268886233306.

🏃 View run bright-fish-925 at: http://127.0.0.1:5000/#/experiments/1/runs/34ba435cac8c4fa983c0f2cb6389f46d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:11:39,416] Trial 9 finished with value: 4.772045907181856 and parameters: {'n_estimators': 400, 'max_depth': 8, 'min_samples_split': 12, 'min_samples_leaf': 11}. Best is trial 8 with value: 4.546268886233306.
[I 2026-09-15 11:11:39,451] A new study created in memory with name: no-name-6d191a84-c2a8-4c8b-80a0-9db89070fb5c

🏃 View run beautiful-robin-84 at: http://127.0.0.1:5000/#/experiments/1/runs/94ef7a647d46464c9c242eab92d67cc5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments/1/runs/0c479e4b38bd42659b58a942c12203dc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:11:53,473] Trial 0 finished with value: 4.40577962945753 and parameters: {'n_estimators': 300, 'learning_rate': 0.03752460374926499, 'max_depth': 9}. Best is trial 0 with value: 4.40577962945753.

🏃 View run clean-swan-234 at: http://127.0.0.1:5000/#/experiments/1/runs/27295050847f418b9c618ff825e64019
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:13,091] Trial 1 finished with value: 4.536486719651614 and parameters: {'n_estimators': 300, 'learning_rate': 0.011059610728403522, 'max_depth': 9}. Best is trial 0 with value: 4.40577962945753.

🏃 View run placid-sponge-502 at: http://127.0.0.1:5000/#/experiments/1/runs/771507d4713640caaab7ece83e58e1d0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:16,996] Trial 2 finished with value: 4.518045695755554 and parameters: {'n_estimators': 100, 'learning_rate': 0.05787417608346397, 'max_depth': 7}. Best is trial 0 with value: 4.40577962945753.

🏃 View run delicate-cod-959 at: http://127.0.0.1:5000/#/experiments/1/runs/5ce664c2ec1440caa2dd1b8f98c4405f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:26,528] Trial 3 finished with value: 4.3825722608797175 and parameters: {'n_estimators': 250, 'learning_rate': 0.15291977365631307, 'max_depth': 9}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run bemused-grouse-422 at: http://127.0.0.1:5000/#/experiments/1/runs/f3d9fb6ad9764cc7abe1a8644be18d6a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:29,343] Trial 4 finished with value: 4.760789709695478 and parameters: {'n_estimators': 100, 'learning_rate': 0.03498190575744764, 'max_depth': 5}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run sneaky-sheep-129 at: http://127.0.0.1:5000/#/experiments/1/runs/97b83db503a548cb835c85ad2dfbd113
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:38,210] Trial 5 finished with value: 4.396663396787168 and parameters: {'n_estimators': 250, 'learning_rate': 0.09095549853573343, 'max_depth': 8}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run traveling-moth-776 at: http://127.0.0.1:5000/#/experiments/1/runs/36e5b6e9466941939201e1ed6d8f7519
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:45,293] Trial 6 finished with value: 4.4629130507712285 and parameters: {'n_estimators': 250, 'learning_rate': 0.0617440175389437, 'max_depth': 6}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run shivering-lark-833 at: http://127.0.0.1:5000/#/experiments/1/runs/96516c3ce2b0444bb661d1ca681f5a7d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:46,297] Trial 7 finished with value: 4.679740040859811 and parameters: {'n_estimators': 50, 'learning_rate': 0.1471376617676226, 'max_depth': 4}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run honorable-hare-984 at: http://127.0.0.1:5000/#/experiments/1/runs/a40235cb347f425096f93ef9b2217989
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:47,885] Trial 8 finished with value: 5.626429628212009 and parameters: {'n_estimators': 50, 'learning_rate': 0.022065329563125038, 'max_depth': 5}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run adaptable-mouse-83 at: http://127.0.0.1:5000/#/experiments/1/runs/4bb94fee05fa411885ec14799b090e12
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

[I 2026-09-15 11:12:53,131] Trial 9 finished with value: 4.4170412775591865 and parameters: {'n_estimators': 100, 'learning_rate': 0.12158752897954846, 'max_depth': 10}. Best is trial 3 with value: 4.3825722608797175.

🏃 View run omniscient-carp-91 at: http://127.0.0.1:5000/#/experiments/1/runs/9739506d4b1a4e3fbaf541ed1a6fc8d8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
🏃 View run Gradient Boost at: http://127.0.0.1:5000/#/experiments/1/runs/935053fa8caa4fceb5f2754335498e89
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

## Model Registery

In [40]:
from mlflow import MlflowClient
client = MlflowClient(tracking_uri=TRACKING_URI)

In [43]:
from mlflow.entities import ViewType

runs = client.search_runs(
    experiment_ids=["1"],
    run_view_type=ViewType.ACTIVE_ONLY,
    max_results=5,
    order_by=["metrics.`best-rmse` ASC"]
)

## Taking out the best runs according to lowest RMSE

In [41]:
def get_best_params(model_name,params):
    if model_name == 'Linear Regression':
        return {}
            
    elif model_name == 'SVR':  
        return {
            'C': float(params["best_C"]),
            'epsilon': float(params["best_epsilon"]),
            'kernel': params["best_kernel"]
        }
        
    elif model_name == 'Decision Tree':
        return {
            'max_depth': int(params["best_max_depth"]),
            'min_samples_split': int(params["best_min_samples_split"]),
            'min_samples_leaf': int(params["best_min_samples_leaf"]),
        }
        
    elif model_name == 'Random Forest':
        return {
            'n_estimators': int(params["best_n_estimators"]),
            'max_depth': int(params["best_max_depth"]),
            'min_samples_split': int(params["best_min_samples_split"]),
            'min_samples_leaf': int(params["best_min_samples_leaf"]),
        }
        
    elif model_name == 'Gradient Boost':
        return {
            'n_estimators': int(params["best_n_estimators"]),
            'learning_rate':float(params["best_learning_rate"]),
            'max_depth': int(params["best_max_depth"]),
        }
        
    else:
        raise ValueError(f"Unknown model name: {model_name}")

In [45]:

for run in runs:
    # print(run.data.tags.get("mlflow.runName"))
    # print(run.info)
    params = run.data.params
    # print(params)
    model = params["model"]
    best_params = get_best_params(model,params)
    print(model)
    print(best_params)
    print(run.data.metrics["best-rmse"])
    print("*"*50)

Gradient Boost
{'n_estimators': 250, 'learning_rate': 0.15291977365631307, 'max_depth': 9}
4.3825722608797175
**************************************************
Random Forest
{'n_estimators': 350, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 8}
4.546268886233306
**************************************************
SVR
{'C': 37.22622766508552, 'epsilon': 0.0035413396633088286, 'kernel': 'rbf'}
4.548722488367539
**************************************************
Decision Tree
{'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 20}
4.806084470053386
**************************************************
Linear Regression
{}
5.297774718297283
**************************************************

In [48]:
for run in runs:
    params = run.data.params
    model = params["model"]
    best_params = get_best_params(model,params)
    classifier = get_model(model,best_params)
    pipeline = Pipeline([
            ('preprocessor',column_transformer),
            ('model',classifier)
            ])
    with mlflow.start_run(nested=True):
        mlflow.log_params(best_params)
        mlflow.log_param("model",model)
        pipeline.fit(X_train,y_train)
        y_pred = pipeline.predict(X_val)
        rmse = root_mean_squared_error(y_val,y_pred)
        mlflow.log_metric("rmse",rmse)
        mlflow.sklearn.log_model(pipeline,artifact_path="model",skops_trusted_types=["scipy.sparse._csr.csr_matrix"])

2026/09/15 14:03:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/15 14:03:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run exultant-fowl-943 at: http://127.0.0.1:5000/#/experiments/1/runs/1fb82dbf423340f1aa1db2c7815ca8c6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/09/15 14:04:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/15 14:04:34 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run illustrious-goat-202 at: http://127.0.0.1:5000/#/experiments/1/runs/7f6bcc51d0a846c7bdc3c8c56e0752d5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/09/15 14:06:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/15 14:06:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/09/15 14:06:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run nervous-gnat-242 at: http://127.0.0.1:5000/#/experiments/1/runs/d22c01c2ccac44b38f0beb4923ec8b4a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/09/15 14:06:27 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026/09/15 14:06:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run shivering-grouse-54 at: http://127.0.0.1:5000/#/experiments/1/runs/22bcaf6e8cb74dbf9a1a8551f11cf453
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

2026/09/15 14:06:30 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.

🏃 View run defiant-moose-258 at: http://127.0.0.1:5000/#/experiments/1/runs/e58d51a2a41d49a7b2066cd062bc7d6a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

## Registering the top 5 models and making one model champion

In [52]:
registered_model_name = "trip-duration-prediction"

In [49]:
runs = client.search_runs(
    experiment_ids=["1"],
    max_results=5,
    order_by=["start_time DESC"]
)

In [53]:
for run in runs:
    run_id = run.info.run_id
    model_uri = f"runs:/{run_id}/model"
    mlflow.register_model(model_uri=model_uri,name = registered_model_name)

Successfully registered model 'trip-duration-prediction'.
2026/09/15 14:15:16 WARNING mlflow.tracking._model_registry.fluent: Run with id e58d51a2a41d49a7b2066cd062bc7d6a has no artifacts at artifact path 'model', registering model based on models:/m-bc0850cca7844bfc80f355f5fc975098 instead
2026/09/15 14:15:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: trip-duration-prediction, version 1
Created version '1' of model 'trip-duration-prediction'.
Registered model 'trip-duration-prediction' already exists. Creating a new version of this model...
2026/09/15 14:15:16 WARNING mlflow.tracking._model_registry.fluent: Run with id 22bcaf6e8cb74dbf9a1a8551f11cf453 has no artifacts at artifact path 'model', registering model based on models:/m-b0b935ed87584a6189cede7f708648cd instead
2026/09/15 14:15:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: trip-duration-prediction, version 2
Created version '2' of model 'trip-duration-prediction'.
Registered model 'trip-duration-prediction' already exists. Creating a new version of this model...
2026/09/15 14:15:16 WARNING mlflow.tracking._model_registry.fluent: Run with id d22c01c2ccac44b38f0beb4923ec8b4a has no artifacts at artifact path 'model', registering model based on models:/m-896232f71b974c5a8fbde8863a6fe17b instead
2026/09/15 14:15:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: trip-duration-prediction, version 3
Created version '3' of model 'trip-duration-prediction'.
Registered model 'trip-duration-prediction' already exists. Creating a new version of this model...
2026/09/15 14:15:16 WARNING mlflow.tracking._model_registry.fluent: Run with id 7f6bcc51d0a846c7bdc3c8c56e0752d5 has no artifacts at artifact path 'model', registering model based on models:/m-cd9dc0e5435548428280d448765f4a93 instead
2026/09/15 14:15:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: trip-duration-prediction, version 4
Created version '4' of model 'trip-duration-prediction'.
Registered model 'trip-duration-prediction' already exists. Creating a new version of this model...
2026/09/15 14:15:16 WARNING mlflow.tracking._model_registry.fluent: Run with id 1fb82dbf423340f1aa1db2c7815ca8c6 has no artifacts at artifact path 'model', registering model based on models:/m-c79110144847427e85c9630a5eaabac1 instead
2026/09/15 14:15:16 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: trip-duration-prediction, version 5
Created version '5' of model 'trip-duration-prediction'.

In [54]:
registered_models = client.search_model_versions(f"name='{registered_model_name}'")
len(registered_models)

5

In [60]:
for registered_model in registered_models:
    run_id = registered_model.run_id
    info = client.get_run(run_id)
    print(info.data.metrics["rmse"])
    print(registered_model.version)

4.383813979383911
5
4.547593586620477
4
4.548722488367539
3
4.806084470053386
2
5.297774718297283
1

In [61]:
best_rmse = 100
best_version = -1
for registered_model in registered_models:
    run_id = registered_model.run_id
    info = client.get_run(run_id)
    rmse = info.data.metrics["rmse"]

    if rmse<best_rmse:
        best_rmse = rmse
        best_version = registered_model.version

In [65]:
client.set_registered_model_alias(name = registered_model_name,alias="Champion",version=best_version)

In [66]:
model_uri = f"models:/{registered_model_name}@Champion"
model = mlflow.sklearn.load_model(model_uri=model_uri)

In [69]:
import joblib

joblib.dump(
    model,
    "./best_model.joblib"
)

['./best_model.joblib']

In [68]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['pickup_hour', 'pickup_day',
                                                   'pickup_month',
                                                   'pickup_weekday',
                                                   'passenger_count',
                                                   'trip_distance']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['PULocationID',
                                                   'DOLocationID',
                                                   'PU_DO'])])),
                ('model',
                 GradientBoostingRegressor(learning_rate=0.15291977365631307,
                                           max_depth=9, n_estimators=250))])

In [70]:
X_test.to_csv('../data/test_data.csv')

In [71]:
y_test.to_csv("../data/test_data_duration.csv")

In [44]:
import joblib
model = joblib.load("./best_model.joblib")

In [50]:
u

,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO
0,15,11,1,6,1.0,2.87,74,239,74_239

In [62]:
z = pd.concat([u,u])

In [63]:
z

,pickup_hour,pickup_day,pickup_month,pickup_weekday,passenger_count,trip_distance,PULocationID,DOLocationID,PU_DO
0,15,11,1,6,1.0,2.87,74,239,74_239
0,15,11,1,6,1.0,2.87,74,239,74_239

In [64]:
i = model.named_steps['preprocessor'].transform(z)

In [65]:
i.shape

(2, 2788)

In [57]:
X['PULocationID'].nunique()

163

In [68]:
pred = model.predict(z)

In [69]:
pred

array([15.75473538, 15.75473538])

In [71]:
pd.isna(z).any()

pickup_hour        False
pickup_day         False
pickup_month       False
pickup_weekday     False
passenger_count    False
trip_distance      False
PULocationID       False
DOLocationID       False
PU_DO              False
dtype: bool